name: Run Act2 Python script with CSV file
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: >
          python -m pip install --upgrade pip

      - name: Run Act2 Python script with CSV file
        run: >
          python convert.py --input data.csv  # Adjust this command as per your
          script's needs
